server:
  port: 8081
system:
  file:
    path: D:/files-here
    name: student_information.csv
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: file-processor-consumer-1
      topic-name: file-processor-topic
