server:
  port: 8080
spring:
  kafka:
    producer:
      topic-name: file-processor-topic
      bootstrap-servers: localhost:9092
      linger-ms: 20
      batch-size: 32768
      max-in-flight-request-per-connection: 1